import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { ThemeProvider } from "./Styles/ThemeProvider";
import StyledComponentsRegistry from "./registry";
import Header from "./components/Header/header";
import Footer from "./components/Footer/footer";

export const metadata: Metadata = {
  title: "Evob",
  description: "Evob plataforma",
>>>>>>> develop
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
=======
    <html lang="pt-BR">
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </StyledComponentsRegistry>
>>>>>>> develop
      </body>
    </html>
  );
}
